fix: prevent cache directory race condition
When running multiple copies of `tsx` in parallel (i.e. with concurrently/npm-run-all), a race condition can occur where the cache directory is created by another process after the exists check has returned false. This results in the following error, because the mkdirSync is trying to create something that already exists:

```
Error: EEXIST: file already exists, mkdir '/tmp/esbuild-kit'
    at Object.mkdirSync (node:fs:1334:3)
```

This fix resolves that by using mkdirSync's recursive mode, where it both creates missing parent directories and also does not error if the directory already exists.